[build]
  base = "notary-site"
  command = "npm run build"
  publish = "notary-site/dist"

# Serve robots.txt and sitemap.xml directly
[[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200
  force = false

[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200
  force = false

# SPA fallback - redirect all other requests to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
